version: '3'
services:
  web:
    image: infracloudio/csvserver:latest
    container_name: infra_solution
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - 9393:9300
    volumes:
      - ./inputFile:/csvserver/inputdata:rw  



