version: '3'
services:
  web:
    image: infracloudio/csvserver:latest
    container_name: infra_solution
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - 9393:9300
    volumes:
      - ./inputFile:/csvserver/inputdata:rw  


  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheusdata:/prometheus
      
volumes:
  prometheusdata:

